Commit with BUG
SystemCheckError: System check identified some issues:

ERRORS:
CandidateApp.JobApplication.job_post: (fields.E304) Reverse accessor 'JobPost.applications' for 'CandidateApp.JobApplication.job_post' clashes with reverse accessor for 'EmployeeApp.Application.job'.
        HINT: Add or change a related_name argument to the definition for 'CandidateApp.JobApplication.job_post' or 'EmployeeApp.Application.job'.
CandidateApp.JobApplication.job_post: (fields.E305) Reverse query name for 'CandidateApp.JobApplication.job_post' clashes with reverse query name for 'EmployeeApp.Application.job'.
        HINT: Add or change a related_name argument to the definition for 'CandidateApp.JobApplication.job_post' or 'EmployeeApp.Application.job'.EmployeeApp.Application.job: (fields.E304) Reverse accessor 'JobPost.applications' for 'EmployeeApp.Application.job' clashes with reverse accessor for 'CandidateApp.JobApplication.job_post'.
        HINT: Add or change a related_name argument to the definition for 'EmployeeApp.Application.job' or 'CandidateApp.JobApplication.job_post'.EmployeeApp.Application.job: (fields.E305) Reverse query name for 'EmployeeApp.Application.job' clashes with reverse query name for 'CandidateApp.JobApplication.job_post'.
        HINT: Add or change a related_name argument to the definition for 'EmployeeApp.Application.job' or 'CandidateApp.JobApplication.job_post'.

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace